[package]
name = "chain-intoiter"
version = "0.4.0"
authors = ["Sergey Shandar"]
description = "Chaining IntoIter"
license = "Apache-2.0"
repository = "https://github.com/rust-common/chain-intoiter"

[dependencies]
